# Application ArgoCD pour l'environnement Dev
# À appliquer : kubectl apply -f argocd/valoria-dev.yaml -n argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valoria-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/emmguardia/Valoria-Argo-Repo.git
    targetRevision: dev
    path: charts/valoria
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: valoria-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
