{{- if eq .Values.sealedSecret.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: valoria-secrets
  namespace: {{ include "valoria.namespace" . }}
spec:
  encryptedData:
    {{- if .Values.sealedSecret.encryptedData }}
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
    {{- else }}
    # Remplis values.yaml -> sealedSecret.encryptedData avec tes valeurs Ag... (kubeseal)
    # Exemple:
    # vite-api-url: Ag...
    # sentry-dsn: Ag...
    example-key: AgREPLACE_WITH_KUBESEAL
    {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: valoria-secrets
      namespace: {{ include "valoria.namespace" . }}
    type: Opaque
{{- end }}
