{{- if eq .Values.sealedSecret.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: valoria-secrets
  namespace: {{ include "valoria.namespace" . }}
spec:
  encryptedData:
    # Remplace ces placeholders avec kubeseal
    example-key: AgREPLACE_WITH_KUBESEAL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: valoria-secrets
      namespace: {{ include "valoria.namespace" . }}
    type: Opaque
{{- end }}
